micronaut-projects/static-website

main/src/main/groovy/io/micronaut/main/SiteMap.groovy

Changed "ot" to "to" under the question "I have a cool idea or feature request for Micronaut - where can I share it?"

Fixed typo in FAQ

---

core/src/main/groovy/io/micronaut/Navigation.groovy
main/src/main/groovy/io/micronaut/main/SiteMap.groovy
main/src/main/groovy/io/micronaut/main/pages/DownloadPage.groovy

This contains the next links: https://github.com/micronaut-projects/micronaut-core/releases/tag/v1.0.0.M1
https://github.com/micronaut-projects/micronaut-core/releases/download/v1.0.0.M1/micronaut-1.0.0.M1.zip
https://github.com/micronaut-projects/micronaut-core/releases/download/v1.0.0.M1/micronaut-docs-1.0.0.M1.zip
https://github.com/micronaut-projects/micronaut-core/releases

Show Download page

---

main/src/main/groovy/io/micronaut/main/pages/DownloadPage.groovy

This corrects the download URL for sdkman and makes some minor adjustments to wording.

Some tweaks to the download page text.

---

main/src/main/resources/modules.yml

Fix spelling error

---

main/src/main/resources/modules.yml

I re-used the `test.svg` as image. Somebody with more skills should create an image later…

Add picocli to documentation

---

main/src/main/js/start/src/App.jsx
main/src/main/js/start/src/components/CodePreview/CodePreview.js
main/src/main/js/start/src/components/CodePreview/index.js
main/src/main/js/start/src/components/FeatureSelector/FeatureSelector.js
main/src/main/js/start/src/components/FeatureSelector/feature-selector.css
main/src/main/js/start/src/components/Footer.js
main/src/main/js/start/src/components/GitHubLink.js
main/src/main/js/start/src/components/InfoButton.js
main/src/main/js/start/src/components/StarterForm.js
main/src/main/js/start/src/components/TwitterLink.js
main/src/main/js/start/src/style.css
main/src/main/js/start/src/utility.js

- Refactor into StarterForm
- Refactor into Footer
- Refactor into CodePreview
- Update Mobile Sizing col
- Migrate theme colors into CSS variables

Component refactor / Mobile Sizing

---

main/src/main/js/start/src/App.jsx
main/src/main/js/start/src/components/FeatureSelector/FeatureAvailable.js
main/src/main/js/start/src/components/FeatureSelector/FeatureSelected.js
main/src/main/js/start/src/components/FeatureSelector/FeatureSelector.js
main/src/main/js/start/src/components/FeatureSelector/feature-selector.css
main/src/main/js/start/src/components/FeatureSelector/index.js
main/src/main/js/start/src/style.css

closes https://github.com/micronaut-projects/micronaut-starter/issues/143
closes https://github.com/micronaut-projects/micronaut-starter/issues/148

Sort Features based on categories, convert feature selector to modal.

---

main/src/main/js/start/src/App.jsx
main/src/main/js/start/src/components/CodePreview/CodePreview.js
main/src/main/js/start/src/components/Diff.js
main/src/main/js/start/src/components/FeatureSelector/FeatureSelector.js
main/src/main/js/start/src/style.css

Adds a UI for Diff

---

main/src/main/resources/freeconsultationform.html

Updates to consultation form in Mautic. Should continue to work exactly the same way.

Update Consultation Form

---

main/src/main/resources/micronautpresentationrequestform.html

Just an update to the form in Mautic. Should continue to work exactly the same way.

Update Micronaut Speaker Request Form

---

main/src/main/js/launch/src/App.jsx
main/src/main/js/launch/src/style.css
main/src/main/js/launch/src/styles/button-row.css

- Addresses https://github.com/micronaut-projects/micronaut-starter/issues/195

BugFix - UI: Text in buttons is cut in mobile #195

---

main/src/main/js/launch/src/components/GitHubLink.js
main/src/main/js/launch/src/components/TwitterLink.js

Color combo wasn't correct on updated icons

Fix background/colors on GitHub and Twitter icons.

---

main/src/main/js/launch/src/App.jsx
main/src/main/js/launch/src/components/CodePreview/code-preview.css
main/src/main/js/launch/src/components/CodePreview/index.js
main/src/main/js/launch/src/components/GitHubLink.js
main/src/main/js/launch/src/components/Header/header.css
main/src/main/js/launch/src/components/StarterForm/StarterForm.js
main/src/main/js/launch/src/components/TwitterLink.js
main/src/main/js/launch/src/style.css
main/src/main/js/launch/src/styles/modal-overrides.css
main/src/main/js/launch/src/styles/utility.css

Cleaned up a number of styling issues, grouped theme styles a bit better.
Refactored cluttered CSS into separate modules
- modal
- utility
- code preview
Fixed issues React was complaining about
- required onChange handler in new Micronaut version
- Default application type not in options array (on start)
Fixed issue where progress indicator pushed down Included features when active.

[Chore] Feature/code clean up 20200430

---

main/src/main/js/launch/src/components/FeatureSelector/FeatureSelector.js

Addresses https://github.com/micronaut-projects/micronaut-starter/issues/183

UI: Sort features by category

---

main/src/main/js/launch/src/App.jsx
main/src/main/js/launch/src/components/StarterForm/StarterForm.js
main/src/main/js/launch/src/constants/index.js

Please see: https://github.com/micronaut-projects/micronaut-starter/issues/289

Retrieve available Micronaut versions from API

---

buildSrc/src/main/groovy/io/micronaut/gradle/BlogTask.groovy
templates/Micronaut.iatemplate/Contents/Resources/document.html

Changes News nav to Blog and removes Events portion from page.

News Navigation Updates

---

pages/foundation/index.html

Changed Garey True with James Kleeh

Updated BOD names

---

README.md

Launch has moved to its own repository

doc: del reference to launch

---

assets/images/discoveryclient.svg
conf/modules.yml

Close: https://github.com/micronaut-projects/static-website/issues/98

link to Micronaut discovery client docs

---

assets/stylesheets/screen.css
posts/2020-05-15-micronaut-now-supports-microsoft-azure-functions.md

- Adds max-width to `.largegoldenratio`
- Adds max-width to `<pre>`
- Updates font sizing to work better on XS screens. (<374px i.e. iPhone 5s)
- Adds line break to Microsoft Azure functions md file, to allow link to wrap.
- closes https://github.com/micronaut-projects/static-website-private/issues/21

Mobile friendly post pages

---

assets/stylesheets/screen.css
buildSrc/src/main/groovy/io/micronaut/gradle/BlogTask.groovy

- closes https://github.com/micronaut-projects/static-website-private/issues/5

Recent Posts Headline in Blog

---

posts/2020-07-31-introduction-to-microcronaut-at-merida-jug.md

blog: intro to micronaut at merida jug

---

buildSrc/src/main/groovy/io/micronaut/download/DownloadPage.groovy

Close: https://github.com/micronaut-projects/static-website-private/issues/41

Add (r) to Download Micronaut

---

buildSrc/src/main/groovy/io/micronaut/gradle/MicronautWebsitePlugin.groovy

See: https://github.com/micronaut-projects/static-website-private/issues/46

Disable Micronaut logos

---

posts/2020-08-03-serverless-micronaut-on-google-cloud-platform.md

@kroegerk this brings the content from the latest on demand webinar to the site
https://objectcomputing.com/products/micronaut/resources/serverless-micronaut-on-google-cloud

Webinar Serverless Micronaut on Google Cloud Platform

---

posts/2020-08-11-deploy-friday-micronaut.md

@kroegerk The post image is missing.

Add Deploy Friday podcast

---

posts/2020-08-14-contributing-to-micronaut-publishing-and-reviewing-local-changes.md

Hero image:
blog post: 
@kroegerk the video is unlisted in our Youtube channel. Please make it public when you publish it.

publishing and reviewing local changes post

---

templates/document.html

See: https://github.com/micronaut-projects/static-website-private/issues/37
See: https://github.com/micronaut-projects/static-website/pull/143

Link to events instead of faq from menu

---

pages/learn.html

Close: https://github.com/micronaut-projects/static-website-private/issues/37

Microcast card

---

assets/stylesheets/screen.css
pages/index.html
pages/support.html

Close. https://github.com/micronaut-projects/static-website-private/issues/31
This is how the button to FAQ looks like:

Link to faq from support

---

buildSrc/src/main/groovy/io/micronaut/gradle/BlogTask.groovy
posts/2020-08-25-hands-on-lab-building-java-cloud-native-applications-with-micronaut-and-oci.md

Blog post about @graemerocher hands-on lab at Oracle live
This is how it looks like:

blog: Oracle Developer live

---

buildSrc/src/main/groovy/io/micronaut/gradle/BlogTask.groovy
posts/2020-08-25-hands-on-lab-building-java-cloud-native-applications-with-micronaut-and-oci.md

Close: https://github.com/micronaut-projects/static-website-private/issues/50

fix: don't suggest same blog post

---

posts/2020-08-28-micronaut-2-launching-the-technology-of-the-future.md

blog: Post about Micronaut 2 Q&A session video

---

assets/stylesheets/screen.css

Close: https://github.com/micronaut-projects/static-website/issues/140

fix: hide navbar overflow

---

assets/images/oracle.svg
buildSrc/src/main/groovy/io/micronaut/guides/GuidesPage.groovy

please, @recursivecodes please review the SVG.

Micronaut oracle category

---

README.md
build.gradle
buildSrc/src/main/groovy/io/micronaut/gradle/RenderSiteTask.groovy
posts/2020-08-31-micronaut-2-aws-lambda.md

This brings @eahrold support for multiple javascript and css files.

Multiple javascript and css

---

posts/2020-09-26-java-mexico-micronaut-live-coding.md

@kroegerk blog post for the session I did yesterday (in Spanish) at Java Mexico.

Add Java Mexico live coding session

---

posts/2020-10-08-micronaut-gradle-plugin.md

@kroegerk If possible I would like to publish this today because I'm writing another post (for publishing it next Monday), and I would like to link to one.
Thanks :)

Graeme's video with Micronaut Gradle plugin

---

assets/stylesheets/screen.css
buildSrc/src/main/groovy/io/micronaut/gradle/BlogTask.groovy
pages/learn.html
posts/2020-04-09-micronaut-now-certified-run-amazon-corretto.md

@sdelamo curious to get your feedback specifically, this eliminates a good deal of the previously existing styling scaffolding to replace it w/ CSS Grid (in order to accomplish simply the rowspan 2 of the tag cloud), I don't think I missed anything responsive-wise that was super-critical and I tried to match the previous spacing as best as possible!

modifies blog posts main site to use css grid, rowspan 2 for tagcloud

---

posts/2020-12-03-micronaut-with-kotlin-webinar.md

still needs video before it can be published; *do not merge until link to YouTube video has been added*

create blog post for Micronaut+Kotlin webinar

---

assets/stylesheets/screen.css

Fixes date length in blog pages

---

build.gradle

I found a typo in the keywords section. Feel free to merge if you want to.

Fixes a typo in the keywords section
